In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.impute import SimpleImputer

In [2]:
df_team=pd.read_csv('team_data.csv')
df_team.describe()

,Unnamed: 0,edate,sample,min,blackmin,whitemin,blackstarter,whitestarter,starters,berri,...,xn_home,xn_attend,xn_out_cont,xn_coach_black,xn_ot,xn_opp_out_cont,xn_opp_coach_black,bl_fw,opp_bl_fw,diff_bl_fw
count,28902.000000,28902.000000,24550.0,28902.000000,28902.000000,28902.000000,28902.000000,28902.000000,28902.000000,28902.000000,...,28144.000000,28086.000000,28143.000000,28148.000000,28148.000000,28141.000000,28146.000000,28148.000000,28146.000000,2.814600e+04
mean,14450.500000,13923.968168,1.0,241.260882,200.591101,40.631306,4.198083,0.801571,4.999689,41.755242,...,0.336969,11.246639,0.039382,0.152468,0.046623,0.039385,0.152467,0.560553,0.560562,-1.990501e-18
std,8343.433076,1376.690005,0.0,7.803229,33.500617,32.752988,0.852155,0.852074,0.019507,14.403395,...,0.384241,5.054770,0.169912,0.306424,0.211375,0.169918,0.306432,0.238435,0.238439,1.383033e-01
min,0.000000,11627.000000,1.0,90.000000,45.000000,0.000000,0.000000,0.000000,3.000000,-10.500000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-7.352941e-01
25%,7225.250000,12777.000000,1.0,240.000000,181.000000,15.000000,4.000000,0.000000,5.000000,31.500000,...,0.000000,7.233000,0.000000,0.000000,0.000000,0.000000,0.000000,0.337107,0.337205,-7.500005e-02
50%,14450.500000,13887.000000,1.0,240.000000,205.000000,36.000000,4.000000,1.000000,5.000000,41.500000,...,0.000000,11.381333,0.000000,0.000000,0.000000,0.000000,0.000000,0.572222,0.572222,0.000000e+00
75%,21675.750000,15061.000000,1.0,240.000000,226.000000,59.000000,5.000000,1.000000,5.000000,51.500000,...,0.666667,14.304417,0.000000,0.000000,0.000000,0.000000,0.000000,0.679167,0.679167,7.500005e-02
max,28901.000000,16175.000000,1.0,340.000000,315.000000,233.000000,5.000000,5.000000,5.000000,110.500000,...,1.000000,38.067000,1.000000,1.000000,4.000000,1.000000,1.000000,1.000000,1.000000,7.352941e-01

In [3]:
df_team = df_team[df_team.columns.drop(list(df_team.filter(regex='rid')))]

In [4]:
df_team.describe()

,Unnamed: 0,edate,sample,min,blackmin,whitemin,blackstarter,whitestarter,starters,berri,...,xn_home,xn_attend,xn_out_cont,xn_coach_black,xn_ot,xn_opp_out_cont,xn_opp_coach_black,bl_fw,opp_bl_fw,diff_bl_fw
count,28902.000000,28902.000000,24550.0,28902.000000,28902.000000,28902.000000,28902.000000,28902.000000,28902.000000,28902.000000,...,28144.000000,28086.000000,28143.000000,28148.000000,28148.000000,28141.000000,28146.000000,28148.000000,28146.000000,2.814600e+04
mean,14450.500000,13923.968168,1.0,241.260882,200.591101,40.631306,4.198083,0.801571,4.999689,41.755242,...,0.336969,11.246639,0.039382,0.152468,0.046623,0.039385,0.152467,0.560553,0.560562,-1.990501e-18
std,8343.433076,1376.690005,0.0,7.803229,33.500617,32.752988,0.852155,0.852074,0.019507,14.403395,...,0.384241,5.054770,0.169912,0.306424,0.211375,0.169918,0.306432,0.238435,0.238439,1.383033e-01
min,0.000000,11627.000000,1.0,90.000000,45.000000,0.000000,0.000000,0.000000,3.000000,-10.500000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-7.352941e-01
25%,7225.250000,12777.000000,1.0,240.000000,181.000000,15.000000,4.000000,0.000000,5.000000,31.500000,...,0.000000,7.233000,0.000000,0.000000,0.000000,0.000000,0.000000,0.337107,0.337205,-7.500005e-02
50%,14450.500000,13887.000000,1.0,240.000000,205.000000,36.000000,4.000000,1.000000,5.000000,41.500000,...,0.000000,11.381333,0.000000,0.000000,0.000000,0.000000,0.000000,0.572222,0.572222,0.000000e+00
75%,21675.750000,15061.000000,1.0,240.000000,226.000000,59.000000,5.000000,1.000000,5.000000,51.500000,...,0.666667,14.304417,0.000000,0.000000,0.000000,0.000000,0.000000,0.679167,0.679167,7.500005e-02
max,28901.000000,16175.000000,1.0,340.000000,315.000000,233.000000,5.000000,5.000000,5.000000,110.500000,...,1.000000,38.067000,1.000000,1.000000,4.000000,1.000000,1.000000,1.000000,1.000000,7.352941e-01

In [5]:
dataTypeSeries=df_team.dtypes
dataTypeSeries

Unnamed: 0              int64
team                   object
edate                   int64
home_team              object
sample                float64
                       ...
xn_opp_out_cont       float64
xn_opp_coach_black    float64
bl_fw                 float64
opp_bl_fw             float64
diff_bl_fw            float64
Length: 200, dtype: object

In [6]:
df_team['home'] = np.where(df_team['team']== df_team['home_team'], '1', '0')
df_team['home']

0        0
1        0
2        1
3        1
4        0
        ..
28897    0
28898    0
28899    1
28900    0
28901    1
Name: home, Length: 28902, dtype: object

In [7]:
df_team = df_team.drop(['home_team', 'opp_team', 'team'], axis=1)

In [8]:
df_team = df_team.drop(['score', 'year', 'coach_black', 'coachid', 'white', 'fracwhite', 'ref1_id', 'ref2_id', 'ref3_id'], axis=1)

In [9]:
df_team = df_team.drop(['edate', 'sample', 'min', 'blackmin', 'whitemin', 'berri', 'out_cont', 'gameid', 'teamgame', 'tm_yr'], axis=1)

In [10]:
df_team = df_team.drop(['televised', 'ot', 'opp_score', 'diff_score', 'margin', 'opp_sample', 'diff_sample',], axis=1)

In [11]:
df_team = df_team.drop(['opp_home', 'diff_home', 'opp_ot', 'diff_ot', 'opp_min', 'diff_min',], axis=1)

In [12]:
df_team = df_team[df_team.columns.drop(list(df_team.filter(regex='white')))]

In [13]:
df_team = df_team[df_team.columns.drop(list(df_team.filter(regex='black')))]

In [14]:
df_team = df_team[df_team.columns.drop(list(df_team.filter(regex='starter')))]

In [15]:
df_team = df_team[df_team.columns.drop(list(df_team.filter(regex='berri')))]

In [16]:
df_team = df_team[df_team.columns.drop(list(df_team.filter(regex='points')))]

In [17]:
df_team = df_team.drop(['opp_win', 'diff_win', 'opp_margin', 'diff_margin', 'min_sum_min',], axis=1)

In [18]:
# Imputation
df_team1 = df_team
imputer = SimpleImputer()
df_team1 = pd.DataFrame(imputer.fit_transform(df_team1))
df_team1.columns = df_team.columns
df_team1.head()

,Unnamed: 0,fouls,fta,ftm,ftmiss,fga,fgm,fgmiss,fg2a,fg2m,...,opp_ftper,diff_ftper,xn_home,xn_attend,xn_out_cont,xn_ot,xn_opp_out_cont,bl_fw,opp_bl_fw,diff_bl_fw
0,0.0,25.0,17.0,14.0,3.0,91.0,38.0,53.0,66.0,28.0,...,0.645161,0.178368,0.336969,12.882000,0.039382,0.0,0.0,0.547222,0.363889,0.183333
1,1.0,23.0,29.0,23.0,6.0,86.0,46.0,40.0,60.0,37.0,...,0.833333,-0.040230,0.336969,13.109334,0.039382,0.0,0.0,0.397222,0.472222,-0.075000
2,2.0,22.0,25.0,13.0,12.0,88.0,37.0,51.0,84.0,37.0,...,0.640000,-0.120000,0.666667,10.956667,0.000000,0.0,0.0,0.497222,0.555556,-0.058333
3,3.0,20.0,23.0,15.0,8.0,87.0,40.0,47.0,80.0,37.0,...,0.842105,-0.189931,1.000000,10.952000,0.000000,0.0,0.0,0.741667,0.729167,0.012500
4,4.0,24.0,30.0,25.0,5.0,91.0,39.0,52.0,87.0,38.0,...,0.809524,0.023809,0.000000,15.798667,0.000000,0.0,0.0,0.491667,0.536111,-0.044444

In [19]:
y=df_team1['win']
X=df_team1.drop(['win'], axis=1)

In [20]:
X.head()
if 'win' in X.columns:
    print("Yes")
else:
    print("No")

No

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [23]:
from sklearn.model_selection import GridSearchCV
param_dict = {"n_estimators":[100,500,1000,2500],
              "max_depth":[1,3,5,10]}
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
gs = GridSearchCV(rf, param_dict, scoring = "f1_macro", 
                  n_jobs = -1, verbose = 2)
gs.fit(X_train, y_train)
print("Best Params: {}".format(gs.best_params_))

C:\Users\Collin\OneDrive\Python\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Collin\OneDrive\Python\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.

Fitting 3 folds for each of 16 candidates, totalling 48 fits

[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:  3.0min
[Parallel(n_jobs=-1)]: Done  48 out of  48 | elapsed:  9.0min finished

Best Params: {'max_depth': 10, 'n_estimators': 2500}

In [24]:
rf1= RandomForestClassifier(max_depth=10, n_estimators=1000)
rf1 = rf1.fit(X_train, y_train)
forest_pred = rf1.predict(X_test)

In [25]:
from sklearn.metrics import f1_score, classification_report
print(classification_report(y_test, forest_pred))
from sklearn.metrics import confusion_matrix
y_pred = gs.predict(X_test)
conmat = confusion_matrix(y_test, y_pred)
print(conmat)

              precision    recall  f1-score   support

         0.0       0.93      0.93      0.93      3570
         1.0       0.93      0.94      0.93      3656

    accuracy                           0.93      7226
   macro avg       0.93      0.93      0.93      7226
weighted avg       0.93      0.93      0.93      7226

[[3329  241]
 [ 238 3418]]

In [26]:
import matplotlib.pyplot as plt
estimators = rf1.estimators_
len(rf1.estimators_)

In C:\Users\Collin\OneDrive\Python\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Collin\OneDrive\Python\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Collin\OneDrive\Python\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In C:\Users\Collin\OneDrive\Python\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Collin\OneDrive\Python\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Collin\OneDrive\Python\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The keymap.all_axes rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Collin\OneDrive\Python\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The animation.avconv_path rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Collin\OneDrive\Python\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The animation.avconv_args rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.

1000